#Get-Mailbox -ResultSize unlimited | Search-Mailbox -identity ops198323 -SearchQuery {Received: 01/01/2019..12/08/2019 } -TargetMailbox alexander.mamin -TargetFolder "SearchLog" -LogOnly -LogLevel Full 
#get-transportserver | Where-Object {$_.Name -notlike "*edge*"} | get-messagetrackinglog  -sender ops198323@russianpost.ru -Start (get-date).AddMonths(-6) -End (get-date).AddHours(-1) | fl Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData
get-messagetrackinglog -Server r00excashub01 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub02 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub03 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub04 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub05 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub06 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub07 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub08 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub09 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server r00excashub10 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server D01EXHUB01 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append
get-messagetrackinglog -Server D01EXHUB02 -sender alexmaslov@newtek-shop.ru -Start (get-date).AddMonths(-3) -End (get-date).AddHours(-1) | ft Timestamp, ClientHostname, ServerHostname, ConnectorId, Source, EventId, InternalMessageId, MessageId, {$_.recipients}, {$_.recipientstatus}, MessageSubject, Sender, MessageLatency, MessageLatencyType, EventData | Out-File C:\scripts\OUTLOOK_LOGS.txt -Width 1024 -Append